프로젝트 초기 세팅
f-lab-edu/food-delivery-subscription-service pull request #2
Opened 2022-05-13 08:53 UTC by dailyzett

- Summary

프로젝트 초기 세팅

- Needs more than 10 min for review?

 10분 미만

- Before i request PR review,

없음
 
- After this PR reviewed,

없음

2022-05-15 12:42 UTC, f-lab-jd requested changes
@dailyzett 고생하셨습니다! 리뷰드린 내용 한번 확인 부탁드리겠습니다. 
그리고 리뷰어로 @dilmah0203 님도 함께 추가 부탁드립니다.

2022-05-15 12:42 UTC, f-lab-jd commented on build.gradle
> +}
@dailyzett  요 부분이 의미하는 내용이 무엇인지 아시나요~?

2022-05-15 12:42 UTC, f-lab-jd commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
@dailyzett 저희는 백엔드쪽만 진행 예정이라 불필요한 의존으로 보입니다.

2022-05-15 12:42 UTC, f-lab-jd commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:mysql://localhost/testdb
@dailyzett 

1. 리소스를 위한 파일로 ooo.`properties` 형식이 아닌 ooo.`yml` 형식도 검토해보셨나요? 
2. 테스트를 위한 초기 설정이라고 하지만, 세준님의 로컬에서만 유의미한 소스코드가 리모트에 반영되는것은 좋지 않습니다. 하나의 설정으로 두분 모두 DB 를 사용하기 위해서는 어떤 방법들이 있을까요?

(cc. @dilmah0203 )

2022-05-15 12:42 UTC, f-lab-jd commented on src/main/resources/static/index.html
> +<h1>테스트페이지</h1>
@dailyzett 백엔드프로젝트이기 때문에 마찬가지로 필요없는 파일입니다.

2022-05-16 05:00 UTC, dailyzett commented on build.gradle
> +}
자바 컴파일 단계에서 애노테이션 소스 코드를 분석하고 처리함을 위해서 입니다. compileOnly인 이유는 애노테이션의 경우 컴파일 단계에서 코드를 변경해주고 에러를 잡아주는 역할을 하기 때문에 런타임에 주입할 필요가 없습니다.

2022-05-16 05:01 UTC, dailyzett commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
@f-lab-jd @dilmah0203 의존 제거 완료 했습니다.

2022-05-16 05:01 UTC, dailyzett commented on src/main/resources/static/index.html
> +<h1>테스트페이지</h1>
@f-lab-jd  의존 제거 완료 했습니다.

2022-05-17 06:51 UTC, dailyzett commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:mysql://localhost/testdb
@f-lab-jd @dilmah0203 최신 커밋에 flyway + h2 DB 이용해서 개발 환경 세팅 완료했습니다! 확인 부탁드립니다.

2022-05-17 14:59 UTC, f-lab-jd approved these changes
고생하셨습니다. 👍  추가로 리뷰드린 내용관련해서 한번 고민해보시고, 수정할 사항이 있다면 수정후 머지해주시면 좋을 것 같습니다.

2022-05-17 14:59 UTC, f-lab-jd commented on build.gradle
> +    runtimeOnly 'com.h2database:h2:2.1.212'
@dailyzett 
바로 위에 있는 `org.projectlombok` 은 버전을 명시하지 않으셨지만, `'com.h2database:h2` 에는 세준님께서 버전을 명시하였는데요. Spring Boot 에서 일부 라이브러리들에 대해서는 의존성 관리해주는것에 대해 알고 계시나요~?

(cc. @dilmah0203)

2022-05-18 06:10 UTC, dailyzett commented on build.gradle
> +    runtimeOnly 'com.h2database:h2:2.1.212'
네 알고 있습니다! mvn repository 에서 복붙하느라 버전 정보를 안지웠네요. 해당 부분 지우고 머지하겠습니다.

2022-05-18 06:30 UTC, merged

2022-05-18 13:08 UTC, f-lab-jd commented on build.gradle
> +    runtimeOnly 'com.h2database:h2:2.1.212'
spring boot dependency management