Feature/5
f-lab-edu/food-delivery-subscription-service pull request #20
Opened 2022-07-02 07:14 UTC by dailyzett

- Summary
  - HttpSession 형식으로 로그인 구현
  - 로그인 이전 URL 인증은 인터셉터를 이용해 구현

- Needs more than 10 min for review?
10분 이상

2022-07-04 14:11 UTC, f-lab-jd requested changes
@dailyzett 고생하셨습니다~
리뷰드린 내용 한번 확인부탁드립니다!

2022-07-04 14:11 UTC, f-lab-jd commented on src/main/java/com/flab/foodrun/domain/login/service/LoginService.java
> +		User findUser = userMapper.selectUserByLoginId(loginId)
@dailyzett `findUser` 는 동사형이어서 변수명으로는 적절하지 않아보입니다.

2022-07-04 14:11 UTC, f-lab-jd commented on src/main/java/com/flab/foodrun/domain/login/service/LoginService.java
> +	public User login(String loginId, String inputPassword) {
@dailyzett 프로그램 안에서 대부분의 변수 특히 메소드의 파라미터는 `input` 의 의미가 포함되지 않을까요~?

2022-07-04 14:11 UTC, f-lab-jd commented on src/main/java/com/flab/foodrun/domain/user/service/UserService.java
> +		if(userMapper.countByLoginId(user.getLoginId()) > 0){
@dailyzett 일관성있는 코드스타일은 혼자 개발 할 때에는 물론 협업을 할 때에 반드시 지켜야하는 습관입니다.   
IntelliJ 의 `Save Action` 플러그인을 사용해보시면 해당 습관을 지키는데에 도움이 될 것 같습니다.

2022-07-04 14:11 UTC, f-lab-jd commented on src/main/java/com/flab/foodrun/web/HomeController.java
> +public class HomeController {
@dailyzett HomeController 의 용도는 무엇인가요? RestfulAPI 설계시 필요한 핸들러인가요~?

2022-07-04 14:11 UTC, f-lab-jd commented on src/main/java/com/flab/foodrun/web/SessionConst.java
> +public abstract class SessionConst {
@dailyzett 단순히 상수를 관리하는 class 인듯한데, abstract class 로 설계하신 이유가 있으신가요~?

2022-07-04 14:11 UTC, f-lab-jd commented on src/main/java/com/flab/foodrun/web/login/LoginController.java
> +		LoginResponseForm responseForm = LoginResponseForm.builder()
@dailyzett RestfulAPI 에서는 `oooForm` 이라는 이름의 dto  객체보다는 `oooResponse` 이름이 더 적합합니다.
그리고  Layered Architecture 에서 Controller 의 역할(책임)은 무엇이라고 생각하시나요~?

2022-07-04 14:11 UTC, f-lab-jd commented on src/main/java/com/flab/foodrun/web/user/UserController.java
>  	public ResponseEntity<User> addUser(@Validated @RequestBody UserSaveForm form) {
@dailyzett 마찬가지로 form 이라는 네이밍은 Restful API 에 적합하지 않습니다.

2022-07-04 14:11 UTC, f-lab-jd commented on src/main/java/com/flab/foodrun/web/user/UserController.java
> +		return new ResponseEntity<>(userService.addUser(form.toEntity()), HttpStatus.CREATED);
@dailyzett 응답 DTO 를 만들어서 리턴하는 API 와 Entity 를 그대로 리턴하는 API 의 기준은 무엇인가요~?
함께 학습했던 객체지향 원칙 SOLID 를 생각했을때, Entity 가 응답 DTO 역할까지 해야하는 것이 맞을지 한번 고민해보시면 좋을 것 같습니다.

2022-07-04 14:11 UTC, f-lab-jd commented on src/main/java/com/flab/foodrun/web/user/form/UserSaveForm.java
>  @Setter // setter 메서드 자동 생성 애노테이션
@dailyzett setter 는 반드시 필요한가요~?

2022-07-04 14:11 UTC, f-lab-jd commented on src/main/java/com/flab/foodrun/web/config/WebConfig.java
> +			.excludePathPatterns("/users", "/login");
@dailyzett `/users` API 도 인증없이 호출이 가능한가요~?

2022-07-04 14:11 UTC, f-lab-jd commented on src/test/java/com/flab/foodrun/domain/login/service/LoginServiceTest.java
> +		assertThat(loginUser.getPassword()).isNotEqualTo(testUser.getPassword());
@dailyzett password 와 id 이외에 다른 상태도 검사하신다면 더 꼼꼼한 테스트가 될 것 같습니다.

2022-07-08 12:56 UTC, dailyzett commented on src/main/java/com/flab/foodrun/domain/login/service/LoginService.java
> +		User findUser = userMapper.selectUserByLoginId(loginId)
findUser 변수명을 과거분사 foundUser 로 변경했습니다.

2022-07-08 12:56 UTC, dailyzett commented on src/main/java/com/flab/foodrun/domain/login/service/LoginService.java
> +	public User login(String loginId, String inputPassword) {
inputPassword 를 password로 변경했습니다.

2022-07-08 13:06 UTC, dailyzett commented on src/main/java/com/flab/foodrun/web/HomeController.java
> +public class HomeController {
@f-lab-jd 로그인 이후 세션 인증이 돼야만 접속할 수 있는 테스트용 HomeController 입니다. 없애는게 나을까요?

2022-07-08 13:08 UTC, dailyzett commented on src/main/java/com/flab/foodrun/web/SessionConst.java
> +public abstract class SessionConst {
@f-lab-jd 추상 클래스로 선언 후 private 생성자를 만들어두면 상수만 모아둘 수 있다고 해서 따로 생성했습니다.

2022-07-08 13:16 UTC, dailyzett commented on src/main/java/com/flab/foodrun/web/login/LoginController.java
> +		LoginResponseForm responseForm = LoginResponseForm.builder()
- 컨트롤러는 URI 정보를 받고 모델에서 처리한 결과를 단순히 반환해주는 역할을 한다고 생각합니다.
- LoginResponse DTO 객체를 빌드하는 과정이 컨트롤러에 있으면 SRP가 지켜지지 않을 거 같아 코드를 아래와 같이 수정했습니다.

```java
	@PostMapping("/login")
	public ResponseEntity<LoginResponse> login(@Validated @RequestBody LoginRequest loginForm,
		@NotNull HttpSession session) {

		User loginUser = loginService.login(loginForm.getLoginId(), loginForm.getPassword());
		session.setAttribute(SessionConst.LOGIN_SESSION, loginUser.getLoginId());
		return new ResponseEntity<>(LoginResponse.getBuild(loginUser), HttpStatus.OK);
	}
```

2022-07-08 13:30 UTC, dailyzett commented on src/main/java/com/flab/foodrun/web/user/UserController.java
> +		return new ResponseEntity<>(userService.addUser(form.toEntity()), HttpStatus.CREATED);
UserSaveResponse dto 객체를 추가하고 이 dto 객체를 리턴하도록 코드 변경했습니다.

```java
	@PostMapping
	public ResponseEntity<UserSaveResponse> addUser(
		@Validated @RequestBody UserSaveRequest userSaveRequest) {

		User newUser = userService.addUser(userSaveRequest.toEntity());
		return new ResponseEntity<>(UserSaveResponse.getBuild(newUser),
			HttpStatus.CREATED);
	}
```

2022-07-08 13:32 UTC, dailyzett commented on src/main/java/com/flab/foodrun/web/user/form/UserSaveForm.java
>  @Setter // setter 메서드 자동 생성 애노테이션
@AllArgsConstructor 와 @Setter 가 안쓰이길래 전부 삭제했습니다.

2022-07-08 13:34 UTC, dailyzett commented on src/main/java/com/flab/foodrun/web/config/WebConfig.java
> +			.excludePathPatterns("/users", "/login");
현재 /users 가 POST 메서드로 회원가입 기능을하고 있어서 인터셉터 목록에서 제외했습니다.

2022-07-08 13:37 UTC, dailyzett commented on src/test/java/com/flab/foodrun/domain/login/service/LoginServiceTest.java
> +		assertThat(loginUser.getPassword()).isNotEqualTo(testUser.getPassword());
패스워드 아이디 외에 이름, 이메일, Role, Status, 핸드폰 번호 체크하는 테스트 코드도 추가하였습니다.

2022-07-16 06:08 UTC, f-lab-jd approved these changes
고생하셨습니다 세준님 👍

2022-07-16 06:08 UTC, f-lab-jd commented on src/main/java/com/flab/foodrun/web/login/dto/LoginResponse.java
> +	public static LoginResponse getBuild(User loginUser) {
@dailyzett  `getBuild` 보다는 `of` 나 `from` 이 더  정적팩토리메소드 패턴에 어울리는 네이밍입니다~

2022-07-16 14:06 UTC, dailyzett commented on src/main/java/com/flab/foodrun/web/login/dto/LoginResponse.java
> +	public static LoginResponse getBuild(User loginUser) {
@f-lab-jd 해당 부분 수정했습니다!

2022-07-16 14:07 UTC, merged