feature/3
f-lab-edu/food-delivery-subscription-service pull request #9
Opened 2022-06-06 15:50 UTC by dailyzett

Summary
회원 가입 기능 구현

Needs more than 10 min for review?
10분 미상

Before i request PR review,
없음

After this PR reviewed,
없음

2022-06-07 14:12 UTC, f-lab-jd requested changes
@dailyzett  고생많으셨습니다! 
리뷰드린 내용 한번 더 확인해주시면 좋을 것 같습니다. 

(cc. @dilmah0203)

2022-06-07 14:12 UTC, f-lab-jd commented on src/main/java/com/flab/foodrun/domain/user/User.java
> +@AllArgsConstructor
@dailyzett 예전에 함께 이야기했던 내용중하나인데요. ㅎㅎ 저희는 학습이 목적이기 때문에, 관습적으로 사용하는 어노테이션들에 대해서 `최초 사용시` 어떤 동작을 하는지 주석으로 남겨주시면 좋을 것 같습니다. 
(cc. @dilmah0203)

2022-06-07 14:12 UTC, f-lab-jd commented on src/main/java/com/flab/foodrun/domain/user/User.java
> +	private Long sequenceId;
@dailyzett  seq  로 하지 않고 sequenceId 로 하신 이유가 있으신가요~?

(cc. @dilmah0203)

2022-06-07 14:12 UTC, f-lab-jd commented on src/main/java/com/flab/foodrun/domain/user/service/UserService.java
> +public interface UserService {
@dailyzett `UserService` 의 경우 인터페이스가 반드시 필요할까요~?

2022-06-07 14:12 UTC, f-lab-jd commented on src/main/java/com/flab/foodrun/domain/user/service/impl/UserServiceImpl.java
> +	private final PasswordEncoder passwordEncoder;
@dailyzett 아래 내용에 대해 한번 설명해주실 수 있을까요~? (lombok 관련 주석은 해주시겠지만, lombok 이 낯선 @dilmah0203 님에게는 읽히지 않는 코드입니다.

1. DI 란 무엇일까요? 
2. 현재 DI 를 어떤 방식으로 하고 있는건가요? 
3. 왜 해당 방식으로 DI 를 하셨나요? 

(cc. @dilmah0203 )

2022-06-07 14:12 UTC, f-lab-jd commented on src/main/java/com/flab/foodrun/domain/user/service/impl/UserServiceImpl.java
> +		if(loginIdCount > 0){
@dailyzett 포맷팅이 적용되지 않은 것 같습니다.

2022-06-07 14:12 UTC, f-lab-jd commented on src/main/java/com/flab/foodrun/domain/user/service/impl/UserServiceImpl.java
> +	private void validateDuplicateUser(String loginId) {
@dailyzett validateDuplicat`ed`User 가 더 적합해보입니다.

2022-06-07 14:12 UTC, f-lab-jd commented on src/main/java/com/flab/foodrun/domain/user/service/impl/UserServiceImpl.java
> +			throw new IllegalStateException("이미 존재하는 회원입니다");
@dailyzett `IllegalStateException` 이 적합한 예외일까요~? [Java Reference 문서](https://docs.oracle.com/javase/7/docs/api/java/lang/IllegalStateException.html) 한번 참고해보시고, 직접 예외를 정의하는것도 고려해주시면 좋을 것 같습니다.

(cc. @dilmah0203 )

2022-06-07 14:12 UTC, f-lab-jd commented on src/main/java/com/flab/foodrun/web/config/SecurityConfig.java
> +		return new BCryptPasswordEncoder();
@dailyzett 어떤 알고리즘으로 암호화가 되나요~?
그리고 해당 암호화 방식을 사용한 이유가 무엇인가요?

(cc. @dilmah0203 )

2022-06-07 14:12 UTC, f-lab-jd commented on src/main/java/com/flab/foodrun/web/user/UserController.java
> +	@PostMapping("/add")
@dailyzett 작성하신 API가 Restful API 일까요~?

(cc. @dilmah0203 )

2022-06-07 14:12 UTC, f-lab-jd commented on src/main/java/com/flab/foodrun/web/user/UserController.java
> +	public Object addUser(@Validated @ModelAttribute("user") UserSaveForm form,
@dailyzett 가장 최상위 부모클래스인 Object 타입을 리턴하도록 하는것이 맞을까요~?
예외 발생시 처리 때문에 고민하신거라면, 

1. 예외 발생도 포함할 수 있는 ResponseDto
2. 예외 발생에 대한 Handler 처리를 책임지는 ControllerAdvice, ExceptionHandler 

에 대해 알아보시고 적용해주시면 좋을 것 같습니다.

(cc. @dilmah0203 )

2022-06-07 14:12 UTC, f-lab-jd commented on src/main/java/com/flab/foodrun/web/user/form/UserSaveForm.java
> + * 기본 주소, 상세 주소
@dailyzett 단순 메모역할을 하고 있는 것 같은데요. 소스코드를 보고 파악할 수 있는 것이어서, 삭제해주셔도 좋을 것 같습니다. (그렇지 않다면.. 앞으로 필드 추가/변경/삭제에 대해 요 주석까지도 관려해주어야 겠죠 ㅎㅎ)

(cc. @dilmah0203 )

2022-06-07 14:12 UTC, f-lab-jd commented on src/test/java/com/flab/foodrun/domain/user/dao/UserDaoTest.java
> +class UserDaoTest {
@dailyzett 테스트클래스명은 테스트하려는 클래스이름(UserMapper)을 포함하는 것이 좋습니다. 

(cc. @dilmah0203 )

2022-06-07 14:12 UTC, f-lab-jd commented on src/test/java/com/flab/foodrun/domain/user/dao/UserDaoTest.java
> +		assertThat(saveCount).isEqualTo(2);
@dailyzett 
insertUser 는 어떠한 결과를 응답할까요? 
해당 count 를 검사하는것만으로 save 메소드에 대한 테스트가 모두 진행되었다고 할 수 있을까요~?

(cc. @dilmah0203)

2022-06-07 14:12 UTC, f-lab-jd commented on src/test/java/com/flab/foodrun/domain/user/service/impl/UserServiceImplTest.java
> +	void 회원가입테스트(){
@dailyzett 테스트코드 메소드에 대한 `일관성`도 지켜주시면 좋을 것 같습니다~! 
꼭 한글로 표현해야하는거라면 `@DisplayName` 을 활용해도 좋을 것 같아요. 

(cc. @dilmah0203)

2022-06-07 14:12 UTC, f-lab-jd commented on src/test/java/com/flab/foodrun/domain/user/service/impl/UserServiceImplTest.java
> +		userService.addUser(form1);
@dailyzett then 에 대한 테스트가 되지 않아보입니다.


(cc. @dilmah0203)

2022-06-07 14:12 UTC, f-lab-jd commented on src/main/resources/mybatis/mapper/user-mapper.xml
> +  <insert id="insertUser" useGeneratedKeys="false" keyProperty="seq_id">
@dailyzett seq_id 라는 컬럼이 있었나요~?

(cc. @dilmah0203)

2022-06-07 14:13 UTC, f-lab-jd commented
추가로 Controller Layer 에 대한 테스트코드도 있으면 좋을 것 같습니다~!

2022-06-08 03:44 UTC, dailyzett commented on src/main/java/com/flab/foodrun/domain/user/service/impl/UserServiceImpl.java
> +	private final PasswordEncoder passwordEncoder;
1. 객체 레퍼런스를 런타임 시점에 외부에서 주입받고 다른 객체와 동적으로 의존 관계가 만들어지는 것을 DI라고 합니다.
2. lombok의 @RequiredArgsConstructor 과 결합해서 생성자 형식으로 주입하고 있습니다.
3. @Autowired를 통한 필드 주입의 경우 DI 컨테이너에 강하게 종속되기때문에  단위 테스트 같은 외부에서 테스트하기 힘들다는 단점이 있습니다. setter 주입의 경우 실제로 한번 의존 관계가 설정되면 잘 안바뀐다는 점도 있고, 순환 참조시 수정자 주입은 빈 생성 시점이 달라 오류를 발생시키지 않기 때문에 생성자 주입 방식을 택했습니다.

2022-06-08 11:03 UTC, dailyzett commented on src/main/java/com/flab/foodrun/domain/user/User.java
> +@AllArgsConstructor
주석 처리 완료했습니다.

2022-06-08 11:04 UTC, dailyzett commented on src/main/java/com/flab/foodrun/domain/user/User.java
> +	private Long sequenceId;
변수명을 축약하면 안 좋다고해서 sequenceId로 정했는데 MySQL 컬럼이 seq_id라 seqId로 변경했습니다.

2022-06-08 11:06 UTC, dailyzett commented on src/main/java/com/flab/foodrun/domain/user/service/impl/UserServiceImpl.java
> +		if(loginIdCount > 0){
전체적으로 포맷팅 점검했습니다.

2022-06-08 11:06 UTC, dailyzett commented on src/test/java/com/flab/foodrun/domain/user/dao/UserDaoTest.java
> +class UserDaoTest {
수정했습니다.

2022-06-08 11:08 UTC, dailyzett commented on src/test/java/com/flab/foodrun/domain/user/service/impl/UserServiceImplTest.java
> +	void 회원가입테스트(){
테스트 코드 메서드 수정 완료했습니다.

2022-06-08 11:14 UTC, dailyzett commented on src/main/resources/mybatis/mapper/user-mapper.xml
> +  <insert id="insertUser" useGeneratedKeys="false" keyProperty="seq_id">
원래 user 테이블의 id였던 컬럼을 MyBatis DAO 로직을 작성할때 헷갈려서 seq_id로 변경했는데 모든 테이블의 id 컬럼을 모두 변경해야하는 문제가 생겨서 다시 id로 변경했습니다.

2022-06-08 12:52 UTC, dailyzett commented on src/main/java/com/flab/foodrun/web/user/form/UserSaveForm.java
> + * 기본 주소, 상세 주소
주석 삭제 완료했습니다.

2022-06-08 13:01 UTC, dailyzett commented on src/main/java/com/flab/foodrun/domain/user/service/UserService.java
> +public interface UserService {
@f-lab-jd UserService를 인터페이스로 따로 둔 이유는 추후에 AOP 적용할 일이 있을 수도 있어서 인터페이스로 선언했습니다. 현재는 단순히 회원 가입 로직만 있는 상태라 인터페이스가 필요없는데 삭제하는 것이 나을까요?

2022-06-09 13:37 UTC, f-lab-jd requested changes
@dailyzett 고생많으셨습니다.
리뷰 드린 내용 한번 더 해주시면 좋을 것 같습니다.
아래 내용은 아직 작성전이신거죠~?
* https://github.com/f-lab-edu/food-run/pull/9/files#r891263259
* https://github.com/f-lab-edu/food-run/pull/9/files#r891268497

2022-06-09 13:37 UTC, f-lab-jd commented on src/main/java/com/flab/foodrun/domain/user/User.java
> +//@Getter, @Setter, @RequiredArgsConstructor,@ToString, @EqualsAndHashCode, @Value를 합친 애노테이션
@dailyzett 
1. 주석에 적어 놓으신 각 어노테이션은 어떤역할을 하나요? 그리고 User 클래스에 해당 어노테이션이 전부 필요할까요? 
2. `@Data` 가 `@Value` 를 포함하나요?

2022-06-09 13:37 UTC, f-lab-jd commented on src/main/java/com/flab/foodrun/domain/user/dao/UserMapper.java
> +//MyBatis @Mapper 애노테이션
@dailyzett 조금 더 상세하게 작성해주실 수 있을까요?

2022-06-09 13:37 UTC, f-lab-jd commented on src/main/java/com/flab/foodrun/domain/user/dao/UserMapper.java
> +	String findLoginIdById(Long id);
@dailyzett 실제 비즈니스로직에는 사용되지 않는 메소드인데, 선언해두신 이유가 무엇인가요? (테스트코드를 위한 메소드 선언은 지양하는게 좋습니다)

그리고 `LoginId` 만 리턴하는게 아닌 `User 객체`를 리턴하는 쿼리와 매핑된 메소드는 필요하지 않을까요~?

2022-06-09 13:37 UTC, f-lab-jd commented on src/main/java/com/flab/foodrun/domain/user/service/UserService.java
> +@Slf4j
@dailyzett 마찬가지로 어노테이션에 대한 설명이 많이 빈약합니다. 면접에서 만약 "이걸 왜 쓰셨나요?" 라고 물었을때, 어떻게 답변하실 것 같나요~?

2022-06-09 13:37 UTC, f-lab-jd commented on src/main/java/com/flab/foodrun/domain/user/service/UserService.java
> +@Service("userService")
@dailyzett Service 의 value 명시한 이유가 있으신가요~?

2022-06-09 13:37 UTC, f-lab-jd commented on src/main/java/com/flab/foodrun/web/user/form/UserSaveForm.java
> +	private String status;
@dailyzett Enum 클래스가 있는데 String 타입으로 받는 이유가 있으신가요~?

2022-06-09 13:37 UTC, f-lab-jd commented on src/main/java/com/flab/foodrun/web/user/form/UserSaveForm.java
> +			.role(Role.CLIENT)
@dailyzett 항상 Client Entity 만 만드는 dto 라면 클래스 이름이 `ClintUserSaveForm` 이 더 적당할 것 같습니다.

2022-06-09 13:37 UTC, f-lab-jd commented on src/main/java/com/flab/foodrun/web/config/SecurityConfig.java
> +	public PasswordEncoder passwordEncoder() {
@dailyzett PasswordEncoder 를 빈으로 등록하신 이유가 무엇인가요~? 어떠한 장/단점이 있을까요?

2022-06-09 13:37 UTC, f-lab-jd commented on src/main/java/com/flab/foodrun/web/user/UserController.java
> +	@PostMapping("/signup")
@dailyzett Restful API 에 대해 조금 더 학습이 필요해보입니다.
Restful API 의 URI 는 어떤 특징을 갖나요?

2022-06-10 13:45 UTC, dailyzett commented on src/main/java/com/flab/foodrun/domain/user/service/impl/UserServiceImpl.java
> +	private void validateDuplicateUser(String loginId) {
@f-lab-jd 해당 부분 수정했습니다!

2022-06-10 13:46 UTC, dailyzett commented on src/test/java/com/flab/foodrun/domain/user/service/impl/UserServiceImplTest.java
> +		userService.addUser(form1);
@f-lab-jd 서비스 테스트 수정 완료 했습니다.

2022-06-10 14:23 UTC, dailyzett commented on src/main/java/com/flab/foodrun/web/config/SecurityConfig.java
> +		return new BCryptPasswordEncoder();
@f-lab-jd 해시 암호화의 한 종류이고, SHA 해시 암호화 방식은 공격자의 브루트 포스(일일이 전부 대입) 공격에 취약하기 때문에 Bcrypt를 선택했습니다.

2022-06-10 14:23 UTC, dailyzett commented on src/main/java/com/flab/foodrun/web/user/UserController.java
> +	@PostMapping("/add")
@f-lab-jd 모든 리소스는 명사로 이뤄져야 하는데 동사라서 RestfulAPI 라고 하긴 어려운 코드입니다.

2022-06-10 14:29 UTC, dailyzett commented on src/test/java/com/flab/foodrun/domain/user/dao/UserDaoTest.java
> +		assertThat(saveCount).isEqualTo(2);
저장된 개수의 카운트 뿐만 아니라 로그인 중복 기능을 체크하기 위해 만들어놓은 countByLoginId 메서드를 이용해 테스트를 보완했습니다.

```java
	@Test
	void insertUser() {
		//given
		int saveCount = 0;
		//when
		saveCount += userMapper.insertUser(user1);
		saveCount += userMapper.insertUser(user2);
		int findUser1Count = userMapper.countByLoginId(user1.getLoginId());
		int findUser2Count = userMapper.countByLoginId(user2.getLoginId());
		//then
		assertThat(saveCount).isEqualTo(2);
		assertThat(findUser1Count).isEqualTo(1);
		assertThat(findUser2Count).isEqualTo(1);
	}
```

2022-06-10 14:30 UTC, dailyzett commented on src/test/java/com/flab/foodrun/domain/user/service/impl/UserServiceImplTest.java
> +		userService.addUser(form1);
해당 테스트 부분의 //then 을 수정 했습니다.

```java
		//then
		verify(mockUserMapper, times(2)).countByLoginId(anyString());
		verify(mockUserMapper, times(2)).insertUser(any(User.class));
		assertThat(findUser1.getLoginId()).isEqualTo(formList.get(0).getLoginId());
		assertThat(findUser2.getLoginId()).isEqualTo(formList.get(1).getLoginId());
```

2022-06-13 00:48 UTC, dailyzett commented on src/main/java/com/flab/foodrun/domain/user/service/impl/UserServiceImpl.java
> +			throw new IllegalStateException("이미 존재하는 회원입니다");
@f-lab-jd RuntimeException 상속받는 _DuplicatedUserIdException_ 로 변경했습니다.

2022-06-13 03:36 UTC, dailyzett commented on src/main/java/com/flab/foodrun/web/user/UserController.java
> +	public Object addUser(@Validated @ModelAttribute("user") UserSaveForm form,
```java
	@PostMapping("/signup")
	public ResponseEntity<User> addUser(@Validated @ModelAttribute UserSaveForm form) {
		return new ResponseEntity<>(userService.addUser(form), HttpStatus.CREATED);
	}
```

다음과 같이 코드 수정했습니다.

2022-06-13 03:39 UTC, dailyzett commented on src/main/java/com/flab/foodrun/domain/user/User.java
> +//@Getter, @Setter, @RequiredArgsConstructor,@ToString, @EqualsAndHashCode, @Value를 합친 애노테이션
1. @Data 에 있는 모든 애노테이션은 필요없어서 필요한 롬복 부분만 쓰도록 코드 변경했습니다.
2. 확인해보니 @Value는 포함 안합니다.

2022-06-13 12:13 UTC, dailyzett commented on src/main/java/com/flab/foodrun/domain/user/dao/UserMapper.java
> +//MyBatis @Mapper 애노테이션
```java
/**
 * MyBatis는 최소 하나의 SqlSessionFactory와 Mapper Interface가 필요
 * Mapper Interface 를 만들어주는 애노테이션
 */
@Mapper
```

주석 수정 했습니다.

2022-06-14 01:05 UTC, dailyzett commented on src/main/java/com/flab/foodrun/domain/user/dao/UserMapper.java
> +	String findLoginIdById(Long id);
1. findLoginIdById() 메서드는 삭제했습니다.
2. User 객체를 리턴하는 쿼리 추가했습니다.

2022-06-14 01:05 UTC, dailyzett commented on src/main/java/com/flab/foodrun/domain/user/service/UserService.java
> +@Slf4j
주석 보완했습니다.

2022-06-14 01:08 UTC, dailyzett commented on src/main/java/com/flab/foodrun/domain/user/service/UserService.java
> +@Service("userService")
인터페이스 구현한 클래스 여러개일 때 주입 지정해주려고 넣었던건데 필요없을거같아 삭제했습니다.

2022-06-14 02:39 UTC, dailyzett commented on src/main/java/com/flab/foodrun/web/user/form/UserSaveForm.java
> +	private String status;
해당 부분 Enum 타입으로 수정했습니다.

2022-06-14 02:39 UTC, dailyzett commented on src/main/java/com/flab/foodrun/web/user/form/UserSaveForm.java
> +			.role(Role.CLIENT)
`Role.CLIENT`를 `this.getRole()`로 변경했습니다.

2022-06-14 14:53 UTC, dailyzett commented on src/main/java/com/flab/foodrun/web/user/UserController.java
> +	@PostMapping("/signup")
Restful API는 "행위는 URI에 포함하지 않는다" 라는 규칙이 있기 때문에 컨트롤러의 /signup 매핑을 제거했습니다.

2022-06-14 18:02 UTC, dailyzett commented on src/main/java/com/flab/foodrun/web/config/SecurityConfig.java
> +	public PasswordEncoder passwordEncoder() {
암호화 방식같은 경우 규정에 따라 변경될수 있는데, 외부 설정 파일에서 의존 주입하면 리턴 코드만 변경하면 쉽게 암호화 알고리즘을 변경할 수 있어 유지보수가 쉬워집니다.

2022-06-15 14:10 UTC, f-lab-jd commented on src/main/java/com/flab/foodrun/domain/user/User.java
> +@Setter // setter 메서드 자동 생성 애노테이션
@dailyzett 일단 Setter 는 유지하고, 불변객체를 만드는것은 별도 issue 로 만들어서 나중에 진행하시죠 ㅎㅎ

2022-06-15 14:11 UTC, f-lab-jd commented on src/main/java/com/flab/foodrun/domain/user/User.java
> +@ToString // toString() 메서드 자동 생성 애노테이션
@dailyzett 요건 사용하지 않는다면 빼셔도 좋을 것 같습니다

2022-06-15 14:11 UTC, f-lab-jd approved these changes
고생 많으셨습니다 👍

2022-06-15 21:24 UTC, dailyzett commented on src/main/java/com/flab/foodrun/domain/user/User.java
> +@Setter // setter 메서드 자동 생성 애노테이션
넵 알겠습니다.

2022-06-15 21:25 UTC, dailyzett commented on src/main/java/com/flab/foodrun/domain/user/User.java
> +@ToString // toString() 메서드 자동 생성 애노테이션
ToString 부분 제거했습니다.

2022-06-15 21:28 UTC, merged